"""initial schema

Revision ID: 54e1c4f200ab
Revises: 
Create Date: 2026-04-09 12:17:05.152138
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector.sqlalchemy

# revision identifiers, used by Alembic.
revision: str = '54e1c4f200ab'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channels',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('channel_type', sa.Enum('WHATSAPP', 'WEB_CHAT', 'FACEBOOK', 'INSTAGRAM', 'EMAIL', name='channel_type'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('customers',
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('channel_user_id', sa.String(length=255), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('shopify_customer_id', sa.String(length=100), nullable=True),
    sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customers_channel_user_id'), 'customers', ['channel_user_id'], unique=False)
    op.create_index(op.f('ix_customers_email'), 'customers', ['email'], unique=False)
    op.create_index(op.f('ix_customers_phone'), 'customers', ['phone'], unique=False)
    op.create_index('ix_customers_phone_email', 'customers', ['phone', 'email'], unique=False)
    op.create_index(op.f('ix_customers_shopify_customer_id'), 'customers', ['shopify_customer_id'], unique=False)
    op.create_table('operators',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'AGENT', name='operator_role'), nullable=False),
    sa.Column('status', sa.Enum('ONLINE', 'OFFLINE', 'AWAY', name='operator_status'), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('verification_token', sa.String(length=255), nullable=True),
    sa.Column('reset_token', sa.String(length=255), nullable=True),
    sa.Column('reset_token_expiry', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_activity', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('shopify_orders',
    sa.Column('shopify_order_id', sa.String(length=100), nullable=False),
    sa.Column('order_number', sa.String(length=100), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=True),
    sa.Column('shopify_customer_id', sa.String(length=100), nullable=True),
    sa.Column('customer_email', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('financial_status', sa.String(length=50), nullable=True),
    sa.Column('fulfillment_status', sa.String(length=50), nullable=True),
    sa.Column('total_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('tracking_number', sa.String(length=255), nullable=True),
    sa.Column('tracking_url', sa.Text(), nullable=True),
    sa.Column('carrier', sa.String(length=100), nullable=True),
    sa.Column('shopify_created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('shopify_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('order_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shopify_order_id')
    )
    op.create_index(op.f('ix_shopify_orders_customer_email'), 'shopify_orders', ['customer_email'], unique=False)
    op.create_index('ix_shopify_orders_email', 'shopify_orders', ['customer_email'], unique=False)
    op.create_index(op.f('ix_shopify_orders_order_number'), 'shopify_orders', ['order_number'], unique=False)
    op.create_index(op.f('ix_shopify_orders_shopify_customer_id'), 'shopify_orders', ['shopify_customer_id'], unique=False)
    op.create_index('ix_shopify_orders_status', 'shopify_orders', ['status'], unique=False)
    op.create_table('shopify_webhook_logs',
    sa.Column('topic', sa.String(length=100), nullable=False),
    sa.Column('shopify_order_id', sa.String(length=100), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('processed', sa.Boolean(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shopify_webhook_logs_shopify_order_id'), 'shopify_webhook_logs', ['shopify_order_id'], unique=False)
    op.create_index('ix_webhook_logs_topic', 'shopify_webhook_logs', ['topic'], unique=False)
    op.create_table('knowledge_documents',
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('file_path', sa.Text(), nullable=True),
    sa.Column('doc_type', sa.Enum('FAQ', 'POLICY', 'PRODUCT', 'GUIDE', 'GENERAL', name='document_type'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'READY', 'ERROR', name='document_status'), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('chunk_count', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('uploaded_by_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['operators.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_knowledge_docs_status', 'knowledge_documents', ['status'], unique=False)
    op.create_index('ix_knowledge_docs_type', 'knowledge_documents', ['doc_type'], unique=False)
    op.create_table('operator_channels',
    sa.Column('operator_id', sa.UUID(), nullable=False),
    sa.Column('channel_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ),
    sa.ForeignKeyConstraint(['operator_id'], ['operators.id'], ),
    sa.PrimaryKeyConstraint('operator_id', 'channel_id')
    )
    op.create_table('operator_logs',
    sa.Column('operator_id', sa.UUID(), nullable=False),
    sa.Column('event', sa.String(length=50), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['operator_id'], ['operators.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_operator_logs_operator_timestamp', 'operator_logs', ['operator_id', 'timestamp'], unique=False)
    op.create_table('threads',
    sa.Column('customer_id', sa.UUID(), nullable=True),
    sa.Column('channel_id', sa.UUID(), nullable=True),
    sa.Column('operator_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'ESCALATED', 'TAKEN', 'INBOX', 'CLOSED', name='thread_status'), nullable=False),
    sa.Column('subject', sa.String(length=500), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('closed_reason', sa.String(length=100), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('escalation_reason', sa.Text(), nullable=True),
    sa.Column('escalated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('inbox_contact_email', sa.String(length=255), nullable=True),
    sa.Column('inbox_contact_phone', sa.String(length=50), nullable=True),
    sa.Column('inbox_note', sa.Text(), nullable=True),
    sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('conversation_summary', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['operator_id'], ['operators.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_threads_channel_status', 'threads', ['channel_id', 'status'], unique=False)
    op.create_index('ix_threads_created', 'threads', ['created_at'], unique=False)
    op.create_index('ix_threads_customer', 'threads', ['customer_id'], unique=False)
    op.create_index('ix_threads_status', 'threads', ['status'], unique=False)
    op.create_table('escalations',
    sa.Column('thread_id', sa.UUID(), nullable=False),
    sa.Column('assigned_operator_id', sa.UUID(), nullable=True),
    sa.Column('priority', sa.Enum('LOW', 'NORMAL', 'HIGH', 'URGENT', name='escalation_priority'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ASSIGNED', 'IN_PROGRESS', 'RESOLVED', 'INBOX', name='escalation_status'), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('conversation_summary', sa.Text(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution_note', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_operator_id'], ['operators.id'], ),
    sa.ForeignKeyConstraint(['thread_id'], ['threads.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('thread_id')
    )
    op.create_index('ix_escalations_operator', 'escalations', ['assigned_operator_id'], unique=False)
    op.create_index('ix_escalations_priority_status', 'escalations', ['priority', 'status'], unique=False)
    op.create_index('ix_escalations_status', 'escalations', ['status'], unique=False)
    op.create_table('inbox_items',
    sa.Column('thread_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=True),
    sa.Column('assigned_operator_id', sa.UUID(), nullable=True),
    sa.Column('channel_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('NEW', 'IN_PROGRESS', 'RESOLVED', 'EXPIRED', name='inbox_status'), nullable=False),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('contact_phone', sa.String(length=50), nullable=True),
    sa.Column('contact_name', sa.String(length=255), nullable=True),
    sa.Column('subject', sa.String(length=500), nullable=True),
    sa.Column('conversation_summary', sa.Text(), nullable=True),
    sa.Column('customer_message', sa.Text(), nullable=True),
    sa.Column('sla_deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('first_response_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('follow_up_count', sa.Integer(), nullable=False),
    sa.Column('last_follow_up_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution_note', sa.Text(), nullable=True),
    sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_operator_id'], ['operators.id'], ),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['thread_id'], ['threads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_inbox_created', 'inbox_items', ['created_at'], unique=False)
    op.create_index('ix_inbox_operator', 'inbox_items', ['assigned_operator_id'], unique=False)
    op.create_index('ix_inbox_sla', 'inbox_items', ['sla_deadline'], unique=False)
    op.create_index('ix_inbox_status', 'inbox_items', ['status'], unique=False)
    op.create_table('knowledge_chunks',
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['knowledge_documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_knowledge_chunks_document', 'knowledge_chunks', ['document_id', 'chunk_index'], unique=False)
    op.create_table('messages',
    sa.Column('thread_id', sa.UUID(), nullable=False),
    sa.Column('sender_type', sa.Enum('CUSTOMER', 'ASSISTANT', 'OPERATOR', 'SYSTEM', name='sender_type'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('content_type', sa.Enum('TEXT', 'IMAGE', 'AUDIO', 'VIDEO', 'DOCUMENT', 'LOCATION', name='content_type'), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('operator_id', sa.UUID(), nullable=True),
    sa.Column('media_url', sa.Text(), nullable=True),
    sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['operator_id'], ['operators.id'], ),
    sa.ForeignKeyConstraint(['thread_id'], ['threads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_messages_external', 'messages', ['external_id'], unique=False)
    op.create_index('ix_messages_sender', 'messages', ['sender_type'], unique=False)
    op.create_index('ix_messages_thread_created', 'messages', ['thread_id', 'created_at'], unique=False)
    op.create_table('escalation_notes',
    sa.Column('escalation_id', sa.UUID(), nullable=False),
    sa.Column('operator_id', sa.UUID(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['escalation_id'], ['escalations.id'], ),
    sa.ForeignKeyConstraint(['operator_id'], ['operators.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('escalation_notes')
    op.drop_index('ix_messages_thread_created', table_name='messages')
    op.drop_index('ix_messages_sender', table_name='messages')
    op.drop_index('ix_messages_external', table_name='messages')
    op.drop_table('messages')
    op.drop_index('ix_knowledge_chunks_document', table_name='knowledge_chunks')
    op.drop_table('knowledge_chunks')
    op.drop_index('ix_inbox_status', table_name='inbox_items')
    op.drop_index('ix_inbox_sla', table_name='inbox_items')
    op.drop_index('ix_inbox_operator', table_name='inbox_items')
    op.drop_index('ix_inbox_created', table_name='inbox_items')
    op.drop_table('inbox_items')
    op.drop_index('ix_escalations_status', table_name='escalations')
    op.drop_index('ix_escalations_priority_status', table_name='escalations')
    op.drop_index('ix_escalations_operator', table_name='escalations')
    op.drop_table('escalations')
    op.drop_index('ix_threads_status', table_name='threads')
    op.drop_index('ix_threads_customer', table_name='threads')
    op.drop_index('ix_threads_created', table_name='threads')
    op.drop_index('ix_threads_channel_status', table_name='threads')
    op.drop_table('threads')
    op.drop_index('ix_operator_logs_operator_timestamp', table_name='operator_logs')
    op.drop_table('operator_logs')
    op.drop_table('operator_channels')
    op.drop_index('ix_knowledge_docs_type', table_name='knowledge_documents')
    op.drop_index('ix_knowledge_docs_status', table_name='knowledge_documents')
    op.drop_table('knowledge_documents')
    op.drop_index('ix_webhook_logs_topic', table_name='shopify_webhook_logs')
    op.drop_index(op.f('ix_shopify_webhook_logs_shopify_order_id'), table_name='shopify_webhook_logs')
    op.drop_table('shopify_webhook_logs')
    op.drop_index('ix_shopify_orders_status', table_name='shopify_orders')
    op.drop_index(op.f('ix_shopify_orders_shopify_customer_id'), table_name='shopify_orders')
    op.drop_index(op.f('ix_shopify_orders_order_number'), table_name='shopify_orders')
    op.drop_index('ix_shopify_orders_email', table_name='shopify_orders')
    op.drop_index(op.f('ix_shopify_orders_customer_email'), table_name='shopify_orders')
    op.drop_table('shopify_orders')
    op.drop_table('operators')
    op.drop_index(op.f('ix_customers_shopify_customer_id'), table_name='customers')
    op.drop_index('ix_customers_phone_email', table_name='customers')
    op.drop_index(op.f('ix_customers_phone'), table_name='customers')
    op.drop_index(op.f('ix_customers_email'), table_name='customers')
    op.drop_index(op.f('ix_customers_channel_user_id'), table_name='customers')
    op.drop_table('customers')
    op.drop_table('channels')
    # ### end Alembic commands ###
